"""Stage 4: Data Packaging and Export.

Packages approved Attack Pools into structured datasets ready for retraining.
Generates automated Data Cards summarizing the adversarial distributions.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path

from src.config import get_settings
from src.core.egocentric_types import AttackPool

logger = logging.getLogger(__name__)


class DataPackager:
    """Handles dataset generation and reporting from approved pools."""

    def __init__(self) -> None:
        self.settings = get_settings()
        self.output_dir = Path(self.settings.data_root) / "exports"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def package_approved_pool(self, pool: AttackPool, version: str) -> str:
        """Package an approved pool into a versioned dataset directory."""
        if pool.status != "approved":
            logger.warning(f"Attempting to package non-approved pool: {pool.pool_id}")
            return ""

        dataset_name = f"Dataset_{version}_{pool.error_category}"
        ds_path = self.output_dir / dataset_name
        ds_path.mkdir(exist_ok=True)
        
        # In a real implementation, this would copy/move the physical images
        # or videos into the ds_path and write a COCO or ActivityNet JSON.
        
        manifest = {
            "dataset_name": dataset_name,
            "created_at": datetime.now().isoformat(),
            "source_error_category": pool.error_category,
            "total_samples": pool.size,
            "entries": [
                {
                    "entry_id": entry.entry_id,
                    "attack": entry.attack_name,
                    "severity": entry.severity
                }
                for entry in pool.entries
            ]
        }
        
        manifest_path = ds_path / "manifest.json"
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)
            
        logger.info(f"Packaged {pool.size} items to {ds_path}")
        return str(ds_path)

    def generate_data_card(self, pool: AttackPool, dataset_path: str) -> str:
        """Generate a Markdown Data Card describing the adversarial dataset."""
        
        # Analyze distribution
        attack_counts: dict[str, int] = {}
        severity_counts: dict[int, int] = {}
        
        for entry in pool.entries:
            attack_counts[entry.attack_name] = attack_counts.get(entry.attack_name, 0) + 1
            severity_counts[entry.severity] = severity_counts.get(entry.severity, 0) + 1
            
        attack_stats = "\n".join([f"- **{k}**: {v}" for k, v in attack_counts.items()])
        severity_stats = "\n".join([f"- **Level {k}**: {v}" for k, v in sorted(severity_counts.items())])
        
        card = f"""# Data Card: Adversarial Retraining Pool
        
## Overview
- **Source Error Category**: {pool.error_category}
- **Dataset Path**: `{dataset_path}`
- **Total Samples**: {pool.size}
- **Generated At**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Attack Distribution
{attack_stats}

## Severity Distribution
{severity_stats}

## Provenance
This dataset was generated by the AdverTest Egocentric Engine. It targets
hard negatives specifically extracted from `{pool.error_category}` failures,
augmented across severities {pool.severity_range[0]} to {pool.severity_range[1]}.
All samples have been reviewed and approved via the Label Studio HITL gate.
"""
        card_path = Path(dataset_path) / "DATA_CARD.md"
        with open(card_path, "w", encoding="utf-8") as f:
            f.write(card)
            
        return card

    def create_gold_standard(self, pool: AttackPool, split_ratio: float = 0.1) -> str:
        """Extract a blind evaluation set from the pool."""
        # Simple simulation: take the last N items as the test set
        test_size = max(1, int(pool.size * split_ratio))
        test_entries = pool.entries[-test_size:]
        
        logger.info(f"Created Gold Standard eval set with {len(test_entries)} items.")
        return f"gold_standard_eval_{len(test_entries)}_items"

    def export_retrain_ready(self, package_path: str, format: str = "coco") -> None:
        """Export annotations to the target retraining format (COCO, YOLO, ActivityNet)."""
        logger.info(f"Exported dataset at {package_path} to format: {format}")
